anchoreConfig:
  policy_engine:
    vulnerabilities:
      matching:
        exclude:
          providers: []
          package_types: []
  analyzer:
    layer_cache_max_gigabytes: 5
    enable_hints: true
    configFile:
      retrieve_files:
        file_list:
          - '/etc/passwd'
          - '/etc/services'
          - '/etc/sudoers'
      secret_search:
        match_params:
          - MAXFILESIZE=10000
          - STOREONMATCH=n
        regexp_match:
          - "AWS_ACCESS_KEY=(?i).*aws_access_key_id( *=+ *).*(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9]).*"
          - "AWS_SECRET_KEY=(?i).*aws_secret_access_key( *=+ *).*(?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=]).*"
          - "PRIV_KEY=(?i)-+BEGIN(.*)PRIVATE KEY-+"
          - "DOCKER_AUTH=(?i).*\"auth\": *\".+\""
          - "API_KEY=(?i).*api(-|_)key( *=+ *).*(?<![A-Z0-9])[A-Z0-9]{20,60}(?![A-Z0-9]).*"
      malware:
        clamav:
          enabled: true
          db_update_enabled: true