{
 "title": "Anchore Enterprise",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "analysis_history_window", "label": "analysis_history_window", "query": "${VAR_ANALYSIS_HISTORY_WINDOW}" }
  ]
 },
 "panels": [
  {
   "title": "Service Up Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count_over_time(flask_http_request_duration_seconds_count{endpoint=\"health_check\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Analysis Throughput (images_analyzed/hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(label_replace({__name__=~\"anchore_.*_success_total\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[1h:]))",
     "legendFormat": "IPS (global - 1hr delta)"
    },
    {
     "expr": "sum(rate(label_replace({__name__=~\"anchore_.*_success_total\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[15m:])) * 3600",
     "legendFormat": "IPS (global - 15m rate)"
    },
    {
     "expr": "max_over_time(sum(rate(label_replace({__name__=~\"anchore_.*_success_total\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[15m:])*3600)[24h:5m])",
     "legendFormat": "IPS Max (global - last 24hrs)"
    },
    {
     "expr": "sum(rate(anchore_import_success_total[5m])) * 3600",
     "legendFormat": "import IPS (all analyzers)"
    },
    {
     "expr": "sum(rate(anchore_analysis_success_total[5m])) * 3600",
     "legendFormat": "central IPS (all analyzers"
    },
    {
     "expr": "rate(anchore_analysis_success_total[5m]) * 3600",
     "legendFormat": "central IPS (per analyzer) {{instance}}"
    },
    {
     "expr": "rate(anchore_import_success_total[5m]) * 3600",
     "legendFormat": "import IPS (per analyzer) {{instance}}"
    }
   ]
  },
  {
   "title": "API: API Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(flask_http_request_duration_seconds_count{job=~\"api.*\", status=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API: API Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=\"api\", status=\"200\"}[$__rate_interval]))",
     "legendFormat": "Success (200s)"
    },
    {
     "expr": "sum(rate(flask_http_request_total{job=\"api\", status!=\"200\"}[$__rate_interval]))",
     "legendFormat": "Failure (non-200s)"
    }
   ]
  },
  {
   "title": "Analysis: Image States / Backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(anchore_global_images_analysis_status{analysis_status=\"not_analyzed\"})",
     "legendFormat": "pending"
    },
    {
     "expr": "avg(anchore_global_images_analysis_status{analysis_status=\"analyzed\"}) - avg(anchore_global_images_record_status{image_status=\"deleting\"})",
     "legendFormat": "analyzed"
    },
    {
     "expr": "avg(anchore_global_images_record_status{image_status=\"deleting\"})",
     "legendFormat": "deleting"
    }
   ]
  },
  {
   "title": "Analyzer: Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(anchore_analyzer_status{state=\"processing\"})",
     "legendFormat": "Analyzing"
    },
    {
     "expr": "sum(anchore_analyzer_status{state=\"waiting\"})",
     "legendFormat": "PollingQueue"
    },
    {
     "expr": "sum(anchore_analyzer_status{state=\"error\"})",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Analysis: Image Analysis Times (Import)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max(max_over_time(increase(anchore_import_time_seconds_sum[1m])[24h:1m]))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(anchore_import_time_seconds_bucket{status=\"success\"}[$analysis_history_window])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(anchore_import_time_seconds_bucket{status=\"success\"}[$analysis_history_window])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(anchore_import_time_seconds_bucket{status=\"success\"}[$analysis_history_window])))",
     "legendFormat": "10th"
    },
    {
     "expr": "min(min_over_time(increase(anchore_import_time_seconds_sum[1m])[24h:1m]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(anchore_import_time_seconds_sum / anchore_import_time_seconds_count)",
     "legendFormat": "AverageAll"
    },
    {
     "expr": "anchore_import_time_seconds_sum / anchore_import_time_seconds_count",
     "legendFormat": "Average_{{job}}"
    }
   ]
  },
  {
   "title": "Analysis: Image Analysis Times (Centralized)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(anchore_analysis_time_seconds_bucket{status=\"success\"}[3h])))",
     "legendFormat": "Max"
    },
    {
     "expr": "histogram_quantile(1e-7, sum by(le) (rate(anchore_analysis_time_seconds_bucket{status=\"success\"}[3h])))",
     "legendFormat": "Min"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(anchore_analysis_time_seconds_bucket{status=\"success\"}[3h])))",
     "legendFormat": "Median"
    },
    {
     "expr": "avg(anchore_analysis_time_seconds_sum / anchore_analysis_time_seconds_count)",
     "legendFormat": "AverageAll"
    },
    {
     "expr": "anchore_analysis_time_seconds_sum / anchore_analysis_time_seconds_count",
     "legendFormat": "Average{{job}}"
    }
   ]
  },
  {
   "title": "Catalog: API Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(flask_http_request_duration_seconds_count{job=~\"catalog.*\", status=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PolicyEngine: API Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(flask_http_request_duration_seconds_count{job=~\"policy-engine.*\", status=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory: Container RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{name=~\"aevolume.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory: Process RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes /1024 /1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory: Container Type RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"aevolume.*\"})",
     "legendFormat": "all"
    },
    {
     "expr": "sum(container_memory_rss{name=~\"aevolume.*catalog.*\"})",
     "legendFormat": "catalogs"
    },
    {
     "expr": "sum(container_memory_rss{name=~\"aevolume.*analyzer.*\"})",
     "legendFormat": "analyzers"
    },
    {
     "expr": "sum(container_memory_rss{name=~\"aevolume.*feed.*\"})",
     "legendFormat": "feed"
    },
    {
     "expr": "sum(container_memory_rss{name=~\"aevolume.*policy.*\"})",
     "legendFormat": "policyengines"
    },
    {
     "expr": "sum(container_memory_rss{name=~\"aevolume.*api.*\"})",
     "legendFormat": "apis"
    }
   ]
  },
  {
   "title": "Memory: Process Type RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(process_resident_memory_bytes[10m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"catalog.*\"}) / 1024 / 1024",
     "legendFormat": "catalogs"
    },
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"policy.*\"}) / 1024 / 1024",
     "legendFormat": "policyengines"
    },
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"analyzer.*\"}) / 1024 / 1024",
     "legendFormat": "analyzers"
    },
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"report.*\"}) / 1024 / 1024",
     "legendFormat": "reports"
    },
    {
     "expr": "sum(process_resident_memory_bytes{instance=~\"api.*\"}) / 1024 / 1024",
     "legendFormat": "apis"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}